import Head from "next/head";
import Image from "next/image";
import axios from "axios";
import { useState } from "react";
import { BsSearch } from "react-icons/bs";
import Wheather from "../components/Wheather.jsx";
import Spinner from "../components/Spinner.jsx";

export default function Home() {
  const [city, setCity] = useState("");
  const [weather, setWeather] = useState({});
  const [loading, setLoading] = useState(false);

  const url = `https://api.openweathermap.org/data/2.5/weather?q=${city}&units=imperial&appid=${process.env.NEXT_PUBLIC_KEY}`;

  const fetchWeather = async (e) => {
    e.preventDefault();
    setLoading(true);
    await axios.get(url).then((res) => {
      setWeather(res.data);
    });
    setCity("");
    setLoading(false);
  };

  console.log("WEATHER", weather);

  if (loading) {
    return <Spinner />;
  } else {
    return (
      <div>
        <Head>
          <title>Weather - Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        {/*  Créer un effet sombre sur le background */}
        <div className="absolute top-0 left-0 right-0 bottom-0 bg-black/40 z-[1]" />
        <Image
          src="/meteo.jpg"
          alt="a sky"
          layout="fill"
          className="object-cover"
        />

        {/*       Search     */}

        <div className="relative flex justify-between items-center max-w-[500px] m-auto pt-4 text-white z-10">
          <form
            onSubmit={fetchWeather}
            className="flex justify-between items-center w-full m-auto p-3 bg-transparent border border-gray-300 text-white rounded-2xl  "
          >
            <div>
              <input
                onChange={(e) => setCity(e.target.value)}
                type="text"
                placeholder="Rechercher une ville"
                className="bg-transparent border-none text-white focus:outline-none text-2xl"
              />
            </div>
            <button onClick={fetchWeather}>
              <BsSearch size={25} />
            </button>
          </form>
        </div>

        {/* Display du résultat */}

        {weather.main && <Wheather data={weather} />}
      </div>
    );
  }
}
